export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  tags: string[];
  content: {
    type: "paragraph" | "code" | "heading";
    value: string;
    language?: string;
  }[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "optimizing-postgres-indexing",
    title: "Optimizing PostgreSQL Indexing for Timeseries Data",
    description: "Deep dive into B-Tree vs BRIN indexes and how partitioning improved query times by 40%.",
    date: "Jul 12, 2026",
    readTime: "8 min read",
    tags: ["Database", "Performance", "SQL"],
    content: [
      { type: "paragraph", value: "When dealing with massive timeseries datasets, traditional B-Tree indexes quickly become a bottleneck due to their size and memory overhead. In a recent project, we were ingesting over 10,000 telemetry events per second into PostgreSQL." },
      { type: "heading", value: "The Problem with B-Trees" },
      { type: "paragraph", value: "B-Tree indexes are excellent for random access lookups, but for append-only timeseries data where queries usually filter by time ranges, the index grows linearly and eventually exceeds RAM, causing severe page faults." },
      { type: "code", language: "sql", value: "CREATE INDEX idx_telemetry_created_at ON telemetry_data(created_at);" },
      { type: "heading", value: "Enter BRIN Indexes" },
      { type: "paragraph", value: "Block Range Indexes (BRIN) store the minimum and maximum values for contiguous blocks of table pages. Because our data is inserted chronologically, the 'created_at' column is naturally sorted on disk." },
      { type: "code", language: "sql", value: "CREATE INDEX brin_telemetry_created_at ON telemetry_data USING BRIN(created_at) WITH (pages_per_range = 128);" },
      { type: "paragraph", value: "This simple change reduced our index size from 45GB to just 12MB. Query planner performance improved by 40% for range queries, and insert latency dropped significantly because the database didn't have to constantly rebalance a massive B-Tree." }
    ]
  },
  {
    slug: "idempotency-distributed-systems",
    title: "Idempotency in Distributed Systems",
    description: "Why retries are dangerous without idempotency keys, and how to implement them effectively.",
    date: "Jun 28, 2026",
    readTime: "5 min read",
    tags: ["Architecture", "Microservices", "Reliability"],
    content: [
      { type: "paragraph", value: "In distributed systems, the network is never reliable. When a service makes an HTTP request to another service and times out, it's impossible to know if the request failed to reach the server, or if the server processed it but the response was lost." },
      { type: "heading", value: "The Danger of Retries" },
      { type: "paragraph", value: "Without idempotency, simply retrying a timed-out 'charge payment' request might result in the user being charged twice. This is why non-idempotent operations must be made idempotent." },
      { type: "code", language: "java", value: "@PostMapping(\"/charge\")\npublic ResponseEntity<?> chargePayment(@RequestHeader(\"Idempotency-Key\") String idempotencyKey, @RequestBody PaymentRequest req) {\n    if (redisTemplate.hasKey(idempotencyKey)) {\n        return ResponseEntity.ok(redisTemplate.opsForValue().get(idempotencyKey));\n    }\n    \n    // Process payment...\n    PaymentResult result = paymentService.process(req);\n    \n    // Save result for future retries\n    redisTemplate.opsForValue().set(idempotencyKey, result, Duration.ofHours(24));\n    return ResponseEntity.ok(result);\n}" },
      { type: "paragraph", value: "By passing a unique Idempotency-Key generated by the client, the server can cache the result of the operation. If a retry occurs, the server simply returns the cached response without re-processing." }
    ]
  }
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
